server:
  forward-headers-strategy: native

proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: openid
  my-apps-mode: InLine
  admin-groups: admin
  oauth2:
    resource-id: shinyproxy
    jwks-url: "http://${KC_INTERNAL_URL}/realms/${KC_REALM}/protocol/openid-connect/certs"
    roles-claim: realm_roles
    username-attribute: preferred_username
  openid:
    auth-url: "http://${DOMAIN}/realms/${KC_REALM}/protocol/openid-connect/auth"
    logout-url: "http://${DOMAIN}/realms/${KC_REALM}/protocol/openid-connect/logout?client_id=shinyproxy&post_logout_redirect_uri=http://localhost:3830"
    token-url: "http://${KC_INTERNAL_URL}/realms/${KC_REALM}/protocol/openid-connect/token"
    jwks-url: "http://${KC_INTERNAL_URL}/realms/${KC_REALM}/protocol/openid-connect/certs"
    # token-url: "https://${KC_INTERNAL_URL}/realms/${KC_REALM}/protocol/openid-connect/token"
    # jwks-url: "https://${KC_INTERNAL_URL}/realms/${KC_REALM}/protocol/openid-connect/certs"
    client-id: "${KC_CLIENT_ID}"
    Client-secret: "${KC_CLIENT_SECRET}"
    username-attribute: email
    roles-claim: realm_roles
  docker:
    internal-networking: true
  specs:
    - id: 01_cellxgene
      display-name: Cellxgene
      description: Single-cell RNA-seq visualization tool
      # container-cmd: [
      #   cellxgene,
      #   launch,
      #   --host,
      #   "0.0.0.0",
      #   /bucket/3tr/test2/pbmc3k.h5ad_uploadedVersion_2.h5ad
      # ]
      # container-cmd: [
      #   sh,
      #   /cxgdata/launch_scripts/test.sh
      # ]
      container-cmd: [
        sh,
        "/cxgdata/launch_scripts/#{proxy.userId}.sh"
      ]
      container-image: cz/cellxgene #entrypoint has been removed
      container-network-connections: [omicsdm-server_sp-net]
      container-volumes: ["s3data_external:/bucket", "cxgdata:/cxgdata"]
      container-env:
        GROUP: 3tr
        DATASET: test2
        FILE: pbmc3k.h5ad_uploadedVersion_2.h5ad
      port: 5005

    - id: 02_demo
      display-name: Shinyproxy demo
      description: Application which demonstrates the basics of a Shiny app
      container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
      container-image: openanalytics/shinyproxy-demo
      # access-groups: [admin, user] #assign the role "user" to all users
      container-network-connections: [omicsdm-server_sp-net]
      container-volumes: ["s3data_external:/bucket"]

    - id: flask-demo
      container-image: openanalytics/shinyproxy-flask-demo
      port: 8080
      container-env:
        SCRIPT_NAME: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH').replaceFirst('/$','')}"
      target-path: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"
      container-network-connections: [omicsdm-server_sp-net]
      container-volumes: ["s3data_external:/bucket"]

logging:
  file:
    name: shinyproxy.log
