PROJ_NAME = "gsva_gene_sets_scoring"

# --- Variable Declarations ---- #
runR = "Rscript --no-save --no-restore --verbose"
logAll = "2>&1"


rule all:
    input:
        report_html=f"out/_main.html",


rule report:
    input:
        rmd="src/report/index.Rmd",
        in0="out/results/z-scored.h5ad",
        # in1="out/results/sessionInfo/sessionInfo.txt",
        # in2="out/results/sessionInfo/platform.rds",
        # in3="out/results/sessionInfo/packages.rds",
    output:
        html="out/_main.html",
        book=directory("out/_book"),
    log:
        "log/report.log",
    shell:
        """
        cp {input.rmd} out/.
        {runR} src/lib/build_report.R | tee {log}
        """

rule z_scoring:
    input:
        in1="in/original.h5ad",
        in2="in/normalised.h5ad",
        in3="in/modules.gmt",
        config="analysis_options.json",
    output:
        out1="out/results/z_scores.tsv",
        out2="out/results/z-scored.h5ad",
        # out2="out/results/sessionInfo/sessionInfo.txt",
        # out3="out/results/sessionInfo/platform.rds",
        # out4="out/results/sessionInfo/packages.rds",
    log:
        "log/z_scoring.log",
    shell:
        """
        venv/bin/python3 src/sc_genesets_z_scoring.py \
            --original_h5ad {input.in1} \
            --normalised_h5ad {input.in2} \
            --gene_sets {input.in3} | tee {log}

        mkdir -p out/results
        cp z_scores.tsv {output.out1}
        cp z-scored.h5ad {output.out2}
        """


rule get_data:
    input:
        config="analysis_options.json",
    output:
        out1="in/original.h5ad",
        out2="in/normalised.h5ad",
        out3="in/modules.gmt",
    log:
        "log/get_data.log",
    shell:
        """
        bash src/get_data.sh | tee {log}  
        """


# 2. Other rules
# include: "rules/renv.smk"
