import requests

# needed for querying keycloak
# the token generated by "bash getKCtokens.sh" lead to "not authorized"

from dotenv import dotenv_values

cfg = dotenv_values("kc.env")


def get_kc_token():
    payload = (
        f"client_id={cfg['CLIENT']}&grant_type=password&"
        f"username={cfg['USER']}&password={cfg['PASSWORD']}"
    )
    headers = {"Content-Type": "application/x-www-form-urlencoded"}
    response = requests.post(  # nosec (don't need to verify on localhost)
        cfg["TOKEN_URL"], data=payload, headers=headers, verify=False
    )

    print(response.text)
    return response.json()["access_token"]


def get_kc_groups():
    token = get_kc_token()
    url = "https://sso.cnag.crg.dev/auth/admin/realms/3TR/groups"
    headers = {"Authorization": f"Bearer {token}"}
    response = requests.get(  # nosec (don't need to verify on localhost)
        url, headers=headers, verify=False
    )
    print(response.json())


get_kc_groups()
